import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <Navbar />
      <body className="min-h-full flex flex-col font-sans" style={{ fontFamily: '"Vanilla Sans", Arial, sans-serif' }}>{children}</body>

      <Footer />
    </html>
  );
}
